# Numpy 기초

In [ ]:
import numpy as np

### 배열 생성

In [ ]:
scalar = 1
scalar

1

In [ ]:
vector = np.array([1,2,3,4,5]) #배열 생성 
vector

array([1, 2, 3, 4, 5])

In [ ]:
vector.shape #벡터의 길이 

(5,)

In [ ]:
vector.dtype #벡터의 타입 

dtype('int64')

In [ ]:
#python list를 이용한 배열 생성, numpy에서 읽을 수 있는 형태 
list = [
    [1,2,3],
    [4,5,6]
]
arr = np.array(list)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
list #python에서 읽을 수 있는 형태 

[[1, 2, 3], [4, 5, 6]]

In [ ]:
arr.size #데이터 수 

6

In [ ]:
arr.shape #배열의 차원

(2, 3)

In [ ]:
arr.shape[0] #배열의 열수 

2

In [ ]:
arr.shape[1] #배열의 행수

3

In [ ]:
arr[0,0] #배열의 원소 접근

1

### 특수한 배열의 생성

In [ ]:
arr = np.arange(10) #1씩 증가하는 1차원 배열 생성
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,10) #3부터 1씩 증가하는 1차원 배열 생성 

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
rg = np.random.default_rng(1) #random number generator

In [ ]:
np.floor(10*rg.random((2,2))) 

array([[5., 9.],
       [1., 9.]])

In [ ]:
np.zeros((5, 3)) #0으로 된 행렬 생성, 괄호 두 개가 함수를 의미 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3)) #유닛행렬 생성

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(2) #단위행렬 생성

array([[1., 0.],
       [0., 1.]])

### 배열 결합

In [ ]:
arr1 = np.array(([1,1], [2,2]))
arr2 = np.array(([3,3], [4,4]))

In [ ]:
arr1

array([[1, 1],
       [2, 2]])

In [ ]:
arr2

array([[3, 3],
       [4, 4]])

In [ ]:
arrv = np.vstack((arr1, arr2)) #2개의 array를 결합 - 상하로 stack
arrv  

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
arrv.shape #차원이 (2,2)에서 (4,2)로 변환됨 

(4, 2)

In [ ]:
arrh = np.hstack((arr1, arr2)) #2개의 array를 결합 - 좌우로 stack 
arrh

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
arrh.shape #차원이 (2,2)에서 (2,4)로 변환됨 

(2, 4)

### 배열의 차원 변환

In [ ]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.base

In [ ]:
arr.shape

(20,)

### 차원 추가

In [ ]:
arr[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [ ]:
arr[:, np.newaxis].shape

(20, 1)

In [ ]:
arr[np.newaxis, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [ ]:
arr[np.newaxis, :].shape

(1, 20)

In [ ]:
arr1 = np.expand_dims(arr, axis=1)

In [ ]:
print(arr1) #행으로 나열된 데이터 
arr1.shape

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


(20, 1)

In [ ]:
arr2 = np.expand_dims(arr, axis=0) #열로 나열된 데이터  
print(arr2.shape)
arr2

(1, 20)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [ ]:
arr.resize((5, 4)) #사이즈 변경 
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr.ravel() #행렬 1차원 변환환

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.T #전치행렬 Transpose of A

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
arr.reshape(4,-1) #차원을 변환, -1이 기본값

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr = arr.reshape(4,5) # 4x5행렬
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr.base 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr.view()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 데이터 타입

In [ ]:
arr = np.arange(20) #arr의 자료형 확인 
type(arr) 

numpy.ndarray

In [ ]:
arr.dtype #arr 데이터의 자료형 확인  

dtype('int64')

In [ ]:
arr = arr.astype(np.float32) #데이터 타입 변환 
arr.dtype

dtype('float32')

In [ ]:
arr #실수로 바뀌었기 때문에 자연수 뒤에 온점이 생성 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [ ]:
arr = np.int8(arr) #데이터 타입 변환 
arr.dtype

dtype('int8')

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int8)

In [ ]:
arr = np.array([1,2,3],dtype = np.int32) # 4바이트 크기의 정수
arr.dtype, arr

(dtype('int32'), array([1, 2, 3], dtype=int32))

In [ ]:
arr = np.array([1,2,3],dtype=np.uint8) # 1바이트 크기의 부호 없는 정수(0~255)
arr.dtype, arr

(dtype('uint8'), array([1, 2, 3], dtype=uint8))

In [ ]:
arr = np.array([1,2,3],dtype=np.float64) # 8바이트 크기의 실수
arr.dtype, arr

(dtype('float64'), array([1., 2., 3.]))

In [ ]:
arr = np.array([1,0,1],dtype=np.bool_)
arr.dtype, arr

(dtype('bool'), array([ True, False,  True]))

In [ ]:
np.iinfo(np.uint8) #데이터 타입의 범위 확인 

iinfo(min=0, max=255, dtype=uint8)

In [ ]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [ ]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

### 슬라이싱/인덱싱

In [ ]:
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(lst)
arr.shape

(3, 3)

In [ ]:
arr[1], arr[-1]

(array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[::2, :]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
arr[:, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

### 배열 조건 연산

In [ ]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr[arr<5] #조건에 맞는 데이터만 산출 

array([1, 2, 3, 4])

In [ ]:
cond = (arr > 5) #변수에 조건을 할당할 수 있음 
arr[cond]

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
cond = (arr > 2) & (arr < 11)
arr[cond]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
cond = (arr > 5) | (arr == 5)
arr[cond]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.any(arr>5) #참이 하나라도 있으면 True 반환 

True

In [ ]:
np.all(arr > 3) #조건이 모두 참인가? 

False

In [ ]:
np.where(arr>5, 1, 0) #조건이 참인 경우 1, 거짓인 경우 0으로 변환 

array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1]])

np.clop(array, min, max)
- 배열의 요소가 min보다 작으면 min으로 변환
- 배열의 요소가 max보다 크면 max로 변환

In [ ]:
np.clip(arr, 5, 8)

array([[5, 5, 5, 5],
       [5, 6, 7, 8],
       [8, 8, 8, 8]])

np.inf : 무한 

np.nan : 결측치 

In [ ]:
arr = np.array([np.inf, np.nan, 3,4,5,np.nan,6,7])
arr

array([inf, nan,  3.,  4.,  5., nan,  6.,  7.])

In [ ]:
is_inf = np.isinf(arr) #데이터 하나씩 판단 
is_inf

array([ True, False, False, False, False, False, False, False])

In [ ]:
np.any(is_inf) #무한인 데이터가 하나라도 있는지? , 


True

In [ ]:
np.all(is_inf) #모든 데이터가 무한인지?

False

In [ ]:
is_nan = np.isnan(arr)
is_nan

array([False,  True, False, False, False,  True, False, False])

In [ ]:
np.any(is_nan), np.all(is_nan)

(True, False)

In [ ]:
np.isfinite(arr) #셀 수 있는 데이터 찾기 

array([False, False,  True,  True,  True, False,  True,  True])

In [ ]:
arr[np.isfinite(arr) == False] #셀 수 없는 데이터 호출 

array([inf, nan, nan])

In [ ]:
arr[np.isfinite(arr) == False] = 0 #셀 수 없는 값을 0으로 변경 
arr

array([0., 0., 3., 4., 5., 0., 6., 7.])

In [ ]:
is_inf = np.isinf(arr) #무한값이 사라짐 
is_inf

array([False, False, False, False, False, False, False, False])

In [ ]:
np.any(is_inf), np.all(is_inf)

(False, False)

In [ ]:
is_nan = np.isnan(arr) #nan 값도 사라짐 
is_nan

array([False, False, False, False, False, False, False, False])

In [ ]:
np.any(is_nan), np.all(is_nan)

(False, False)

### 마스킹

In [ ]:
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(lst)
arr.shape

(3, 3)

In [ ]:
mask = [True, False, True] #필터링 
arr[:, mask] #슬라이싱으로 범위 지정, 행과 열에 대한 판단 

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
mask = arr > 5 #스칼라에 대한 판단 
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
arr[mask] #true 값만 변환 

array([6, 7, 8, 9])

### Broadcasting
배열이 다른 값들 간의 계산이 가능하도록 함.

형태는 더 큰 차원에 맞춘다.

단, row 또는 column 크기가 같아야 복사가 가능하다. 1로 표현된 부분만 strech 가능